/*
    Table Schema Setup - for Holdings, Daily_Prices, Currencies 
*/

create table if not exists public.holdings (
    id bigint generated by default as identity primary key,
    ticker text not null,
    shares_owned numeric(20,6) not null check (shares_owned >= 0),
    cost_per_share numeric(20,6) not null check (cost_per_share >= 0),
    currency text not null,
    platform text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.daily_prices (
    id bigint generated by default as identity primary key,
    holding_id bigint not null references public.holdings(id) on delete cascade,
    price_per_share numeric(20,6) not null check (price_per_share >= 0),
    price_date date not null,
    market_value numeric(20,6) not null,
    profit numeric(20,6) not null,
    market_value_sgd numeric(20,6) not null,
    profit_sgd numeric(20,6) not null,
    created_at timestamptz not null default now(),
    unique (holding_id, price_date)
);

create table if not exists public.currencies (
    id bigint generated by default as identity primary key,
    currency text not null,
    rate numeric(20,6) not null check (rate > 0),
    rate_date date not null,
    created_at timestamptz not null default now(),
    unique (currency, rate_date)
);

/*
    Indexes created for quick lookup for common queries - TO CHECK
*/

create index if not exists idx_holdings_ticker
    on public.holdings (ticker);

create index if not exists idx_daily_prices_holding_id
    on public.daily_prices (holding_id);

create index if not exists idx_daily_prices_ticker_price_date
    on public.daily_prices (ticker, price_date);

create index if not exists idx_currencies_currency_rate_date
    on public.currencies (currency, rate_date);

/*
    Triggers for auto-updates of latest updated data (timestamps) - TBC
*/

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_holdings_set_updated_at on public.holdings;

create trigger trg_holdings_set_updated_at
before update on public.holdings
for each row
execute function public.set_updated_at();