/*
    Table Schema Setup - for Holdings, Daily_Prices, Currencies, Trades,
    Cash_Accounts, Cash_Ledger, Cash_Snapshots
*/

create table if not exists public.holdings (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    ticker text not null,
    shares_owned numeric(20,6) not null default 0 check (shares_owned >= 0),
    invested_amount numeric(20,6) not null default 0 check (invested_amount >= 0),
    currency text not null,
    platform text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, ticker, platform, currency)
);

create table if not exists public.daily_prices (
    id bigint generated by default as identity primary key,
    ticker text not null,
    price_per_share numeric(20,6) not null check (price_per_share >= 0),
    price_date date not null,
    created_at timestamptz not null default now(),
    unique (ticker, price_date)
);

create table if not exists public.currencies (
    id bigint generated by default as identity primary key,
    currency text not null,
    rate numeric(20,6) not null check (rate > 0),
    rate_date date not null,
    created_at timestamptz not null default now(),
    unique (currency, rate_date)
);

create table if not exists public.trades (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    holding_id bigint references public.holdings(id) on delete cascade,
    ticker text not null,
    trade_type text not null check (trade_type in ('BUY', 'SELL')),
    currency text not null,
    cash_amount numeric(20,6) not null check (cash_amount > 0),
    shares numeric(20,6) not null check (shares > 0),
    platform text not null,
    traded_at timestamptz not null,
    created_at timestamptz not null default now()
);

create table if not exists public.portfolio_snapshots (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    holding_id bigint not null references public.holdings(id) on delete cascade,
    snapshot_date date not null,
    shares_owned numeric(20,6) not null,
    invested_amount numeric(20,6) not null,
    price_per_share numeric(20,6) not null,
    fx_rate numeric(20,6) not null,
    market_value numeric(20,6) not null,
    market_value_sgd numeric(20,6) not null,
    unrealized_profit numeric(20,6) not null,
    unrealized_profit_sgd numeric(20,6) not null,
    created_at timestamptz not null default now(),
    unique (holding_id, snapshot_date)
);

create table if not exists public.cash_accounts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    platform text not null,
    currency text not null,
    balance numeric(20,6) not null default 0 check (balance >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, platform, currency)
);

create table if not exists public.cash_snapshots (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    cash_account_id bigint not null references public.cash_accounts(id) on delete cascade,
    snapshot_date date not null,
    platform text not null,
    currency text not null,
    balance numeric(20,6) not null,
    fx_rate numeric(20,6) not null,
    balance_sgd numeric(20,6) not null,
    created_at timestamptz not null default now(),
    unique (cash_account_id, snapshot_date)
);

create table if not exists public.cash_ledger (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    platform text not null,
    entry_type text not null check (entry_type in ('DEPOSIT', 'WITHDRAWAL', 'TRADE_BUY', 'TRADE_SELL', 'FX_EXCHANGE')),
    currency text not null,
    amount numeric(20,6) not null check (amount > 0),
    counter_currency text,
    counter_amount numeric(20,6),
    fx_rate numeric(20,6),
    trade_id bigint references public.trades(id) on delete set null,
    note text,
    created_at timestamptz not null default now(),
    constraint chk_cash_ledger_fx_fields
        check (
            (
                entry_type in ('DEPOSIT', 'WITHDRAWAL')
                and counter_currency is null
                and counter_amount is null
                and fx_rate is null
                and trade_id is null
            )
            or
            (
                entry_type in ('TRADE_BUY', 'TRADE_SELL')
                and trade_id is not null
                and counter_currency is null
                and counter_amount is null
                and fx_rate is null
            )
            or
            (
                entry_type = 'FX_EXCHANGE'
                and counter_currency is not null
                and counter_currency <> currency
                and counter_amount is not null
                and fx_rate is not null
                and trade_id is null
            )
        )
);

/*
    Indexes created for quick lookup for common queries - TO CHECK
*/

create index if not exists idx_holdings_user_id
    on public.holdings (user_id);

create index if not exists idx_holdings_user_id_ticker
    on public.holdings (user_id, ticker);

create index if not exists idx_trades_user_id
    on public.trades (user_id);

create index if not exists idx_trades_holding_id_traded_at
    on public.trades (holding_id, traded_at desc);

create index if not exists idx_trades_user_id_ticker_platform_currency
    on public.trades (user_id, ticker, platform, currency);

create index if not exists idx_portfolio_snapshots_user_id
    on public.portfolio_snapshots (user_id);

create index if not exists idx_portfolio_snapshots_holding_id_snapshot_date
    on public.portfolio_snapshots (holding_id, snapshot_date desc);

create index if not exists idx_portfolio_snapshots_user_id_snapshot_date
    on public.portfolio_snapshots (user_id, snapshot_date desc);

create index if not exists idx_cash_ledger_user_id
    on public.cash_ledger (user_id);

create index if not exists idx_cash_ledger_user_id_platform_currency_created_at
    on public.cash_ledger (user_id, platform, currency, created_at desc);

create index if not exists idx_cash_ledger_entry_type
    on public.cash_ledger (entry_type);

create index if not exists idx_cash_ledger_trade_id
    on public.cash_ledger (trade_id);

create index if not exists idx_cash_snapshots_user_id
    on public.cash_snapshots (user_id);

create index if not exists idx_cash_snapshots_cash_account_id_snapshot_date
    on public.cash_snapshots (cash_account_id, snapshot_date desc);

create index if not exists idx_cash_snapshots_user_id_snapshot_date
    on public.cash_snapshots (user_id, snapshot_date desc);

create index if not exists idx_cash_snapshots_user_platform_currency_snapshot_date
    on public.cash_snapshots (user_id, platform, currency, snapshot_date desc);

/*
    Triggers for auto-updates of latest updated data (timestamps) - TBC
*/

-- Trigger functions
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_holdings_set_updated_at on public.holdings;

create trigger trg_holdings_set_updated_at
before update on public.holdings
for each row
execute function public.set_updated_at();

drop trigger if exists trg_cash_accounts_set_updated_at on public.cash_accounts;

create trigger trg_cash_accounts_set_updated_at
before update on public.cash_accounts
for each row
execute function public.set_updated_at();

/*
    BEFORE INSERT trigger on trades:
    - resolve holding_id if missing
    - auto-create holding on BUY if it does not exist
    - reject SELL if holding does not exist
*/
create or replace function public.resolve_trade_holding()
returns trigger
language plpgsql
as $$
declare
    v_holding_id bigint;
    v_holding_user_id uuid;
begin
    -- If holding_id is already provided, validate it belongs to the same user
    if new.holding_id is not null then
        select h.user_id
        into v_holding_user_id
        from public.holdings h
        where h.id = new.holding_id;

        if v_holding_user_id is null then
            raise exception 'Holding % does not exist', new.holding_id;
        end if;

        if v_holding_user_id <> new.user_id then
            raise exception 'Holding % does not belong to user %', new.holding_id, new.user_id;
        end if;

        return new;
    end if;

    -- Try to find an existing holding for this user using ticker/platform/currency
    select h.id
    into v_holding_id
    from public.holdings h
    where h.user_id = new.user_id
      and h.ticker = new.ticker
      and h.platform = new.platform
      and h.currency = new.currency
    limit 1;

    if v_holding_id is not null then
        new.holding_id := v_holding_id;
        return new;
    end if;

    -- If not found and this is a BUY, create the holding automatically
    if new.trade_type = 'BUY' then
        insert into public.holdings (
            user_id,
            ticker,
            shares_owned,
            invested_amount,
            currency,
            platform
        )
        values (
            new.user_id,
            new.ticker,
            0,
            0,
            new.currency,
            new.platform
        )
        returning id into v_holding_id;

        new.holding_id := v_holding_id;
        return new;
    end if;

    -- If not found and this is a SELL, reject it
    raise exception
        'Cannot SELL: no holding exists for user %, ticker %, platform %, currency %',
        new.user_id, new.ticker, new.platform, new.currency;
end;
$$;

drop trigger if exists trg_trades_resolve_holding on public.trades;

create trigger trg_trades_resolve_holding
before insert on public.trades
for each row
execute function public.resolve_trade_holding();


/*
    AFTER INSERT trigger on trades:
    - BUY: add shares and cash_amount to holdings
    - SELL: validate shares, reduce shares, reduce invested_amount by average cost basis
*/
create or replace function public.apply_trade_to_holding()
returns trigger
language plpgsql
as $$
declare
    v_current_shares numeric(20,6);
    v_current_invested numeric(20,6);
    v_holding_user_id uuid;
    v_avg_cost numeric(20,6);
    v_cost_reduction numeric(20,6);
    v_remaining_shares numeric(20,6);
begin
    select h.user_id, h.shares_owned, h.invested_amount
    into v_holding_user_id, v_current_shares, v_current_invested
    from public.holdings h
    where h.id = new.holding_id
    for update;

    if not found then
        raise exception 'Holding % not found for trade %', new.holding_id, new.id;
    end if;

    if v_holding_user_id <> new.user_id then
        raise exception 'Trade user_id does not match holding owner';
    end if;

    if new.trade_type = 'BUY' then
        update public.holdings
        set shares_owned = shares_owned + new.shares,
            invested_amount = invested_amount + new.cash_amount
        where id = new.holding_id;

        return new;
    end if;

    -- SELL logic
    if new.shares > v_current_shares then
        raise exception
            'Cannot SELL %.6f shares: holding only has %.6f shares',
            new.shares, v_current_shares;
    end if;

    if v_current_shares = 0 then
        raise exception 'Cannot SELL from holding % with zero shares', new.holding_id;
    end if;

    v_avg_cost := v_current_invested / v_current_shares;
    v_cost_reduction := new.shares * v_avg_cost;

    v_remaining_shares := v_current_shares - new.shares;

    -- Fully exited position: keep trade history but remove the now-empty holding row.
    if v_remaining_shares <= 0 then
        update public.trades
        set holding_id = null
        where holding_id = new.holding_id;

        delete from public.holdings
        where id = new.holding_id;

        return new;
    end if;

    update public.holdings
    set shares_owned = v_remaining_shares,
        invested_amount = greatest(invested_amount - v_cost_reduction, 0)
    where id = new.holding_id;

    return new;
end;
$$;

drop trigger if exists trg_trades_apply_to_holding on public.trades;

create trigger trg_trades_apply_to_holding
after insert on public.trades
for each row
execute function public.apply_trade_to_holding();

/*
    BEFORE INSERT trigger on trades:
    - verify a cash account exists for user/platform/currency
    - verify BUY trades have sufficient cash balance before the trade is accepted
*/
create or replace function public.check_trade_cash_balance()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_balance numeric(20,6);
begin
    if new.trade_type <> 'BUY' then
        return new;
    end if;

    select ca.balance
    into v_balance
    from public.cash_accounts ca
    where ca.user_id = new.user_id
      and ca.platform = new.platform
      and ca.currency = new.currency
    for update;

    if not found then
        raise exception
            'No cash account found for user %, platform %, currency %',
            new.user_id, new.platform, new.currency;
    end if;

    if v_balance < new.cash_amount then
        raise exception
            'Insufficient cash balance for user %, platform %, currency %: available %, required %',
            new.user_id, new.platform, new.currency, v_balance, new.cash_amount;
    end if;

    return new;
end;
$$;

drop trigger if exists trg_trades_check_cash_balance on public.trades;

create trigger trg_trades_check_cash_balance
before insert on public.trades
for each row
execute function public.check_trade_cash_balance();

/*
    AFTER INSERT trigger on trades:
    - post the cash movement into cash_ledger for BUY and SELL trades
*/
create or replace function public.apply_trade_to_cash_ledger()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if new.trade_type = 'BUY' then
        insert into public.cash_ledger (
            user_id,
            platform,
            entry_type,
            currency,
            amount,
            trade_id,
            note
        )
        values (
            new.user_id,
            new.platform,
            'TRADE_BUY',
            new.currency,
            new.cash_amount,
            new.id,
            'Auto-posted from trade BUY'
        );
        return new;
    end if;

    insert into public.cash_ledger (
        user_id,
        platform,
        entry_type,
        currency,
        amount,
        trade_id,
        note
    )
    values (
        new.user_id,
        new.platform,
        'TRADE_SELL',
        new.currency,
        new.cash_amount,
        new.id,
        'Auto-posted from trade SELL'
    );

    return new;
end;
$$;

drop trigger if exists trg_trades_apply_to_cash_ledger on public.trades;

create trigger trg_trades_apply_to_cash_ledger
after insert on public.trades
for each row
execute function public.apply_trade_to_cash_ledger();

/*
    BEFORE INSERT trigger on cash_ledger:
    - ensure the source cash account exists for every ledger row
    - ensure the destination cash account exists for FX exchange rows
*/
create or replace function public.ensure_cash_accounts_for_ledger()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    insert into public.cash_accounts (user_id, platform, currency)
    values (new.user_id, new.platform, new.currency)
    on conflict (user_id, platform, currency) do nothing;

    if new.entry_type = 'FX_EXCHANGE' then
        insert into public.cash_accounts (user_id, platform, currency)
        values (new.user_id, new.platform, new.counter_currency)
        on conflict (user_id, platform, currency) do nothing;
    end if;

    return new;
end;
$$;

drop trigger if exists trg_cash_ledger_ensure_accounts on public.cash_ledger;

create trigger trg_cash_ledger_ensure_accounts
before insert on public.cash_ledger
for each row
execute function public.ensure_cash_accounts_for_ledger();

/*
    AFTER INSERT trigger on cash_ledger:
    - apply deposits and sell proceeds to the source cash account
    - apply withdrawals and buy cash movements as debits
    - apply FX exchange as a debit on one cash account and a credit on the counter account
*/
create or replace function public.apply_cash_ledger_to_accounts()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_updated_balance numeric(20,6);
begin
    if new.entry_type in ('DEPOSIT', 'TRADE_SELL') then
        update public.cash_accounts
        set balance = balance + new.amount
        where user_id = new.user_id
          and platform = new.platform
          and currency = new.currency
        returning balance into v_updated_balance;

        if not found then
            raise exception
                'Cash account not found for user %, platform %, currency %',
                new.user_id, new.platform, new.currency;
        end if;

        return new;
    end if;

    if new.entry_type in ('WITHDRAWAL', 'TRADE_BUY') then
        update public.cash_accounts
        set balance = balance - new.amount
        where user_id = new.user_id
          and platform = new.platform
          and currency = new.currency
          and balance >= new.amount
        returning balance into v_updated_balance;

        if not found then
            raise exception
                'Insufficient cash balance for user %, platform %, currency %: required %',
                new.user_id, new.platform, new.currency, new.amount;
        end if;

        return new;
    end if;

    if new.entry_type = 'FX_EXCHANGE' then
        update public.cash_accounts
        set balance = balance - new.amount
        where user_id = new.user_id
          and platform = new.platform
          and currency = new.currency
          and balance >= new.amount
        returning balance into v_updated_balance;

        if not found then
            raise exception
                'Insufficient cash balance for FX exchange on user %, platform %, currency %: required %',
                new.user_id, new.platform, new.currency, new.amount;
        end if;

        update public.cash_accounts
        set balance = balance + new.counter_amount
        where user_id = new.user_id
          and platform = new.platform
          and currency = new.counter_currency
        returning balance into v_updated_balance;

        if not found then
            raise exception
                'Target cash account not found for FX exchange on user %, platform %, currency %',
                new.user_id, new.platform, new.counter_currency;
        end if;

        return new;
    end if;

    raise exception 'Unsupported cash ledger entry type: %', new.entry_type;
end;
$$;

drop trigger if exists trg_cash_ledger_apply_to_accounts on public.cash_ledger;

create trigger trg_cash_ledger_apply_to_accounts
after insert on public.cash_ledger
for each row
execute function public.apply_cash_ledger_to_accounts();

/*
    Policies for Holdings and Trades (by user),
    and daily_prices and currencies (readable by authenticated users)
*/

-- RLS for all tables
alter table public.holdings enable row level security;
alter table public.trades enable row level security;
alter table public.daily_prices enable row level security;
alter table public.currencies enable row level security;
alter table public.portfolio_snapshots enable row level security;
alter table public.cash_accounts enable row level security;
alter table public.cash_ledger enable row level security;
alter table public.cash_snapshots enable row level security;

-- By User:
-- Holdings Policies

drop policy if exists "users can view own holdings" on public.holdings;

create policy "users can view own holdings"
on public.holdings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own holdings" on public.holdings;

create policy "users can insert own holdings"
on public.holdings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can update own holdings" on public.holdings;

create policy "users can update own holdings"
on public.holdings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own holdings" on public.holdings;

create policy "users can delete own holdings"
on public.holdings
for delete
to authenticated
using (auth.uid() = user_id);

-- Trades Policies

drop policy if exists "users can view own trades" on public.trades;

create policy "users can view own trades"
on public.trades
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own trades" on public.trades;

create policy "users can insert own trades"
on public.trades
for insert
to authenticated
with check (auth.uid() = user_id);

-- Portfolio Snapshots Policies
drop policy if exists "users can view own portfolio_snapshots" on public.portfolio_snapshots;
create policy "users can view own portfolio_snapshots"
on public.portfolio_snapshots
for select
to authenticated
using (auth.uid() = user_id);

-- Cash Accounts Policies

drop policy if exists "users can view own cash_accounts" on public.cash_accounts;

create policy "users can view own cash_accounts"
on public.cash_accounts
for select
to authenticated
using (auth.uid() = user_id);

-- Cash Ledger Policies

drop policy if exists "users can view own cash_ledger" on public.cash_ledger;

create policy "users can view own cash_ledger"
on public.cash_ledger
for select
to authenticated
using (auth.uid() = user_id);

-- Cash Snapshots Policies

drop policy if exists "users can view own cash_snapshots" on public.cash_snapshots;

create policy "users can view own cash_snapshots"
on public.cash_snapshots
for select
to authenticated
using (auth.uid() = user_id);

-- Public/Authenticated Reads
-- Daily_Prices Policies

drop policy if exists "authenticated users can read daily_prices" on public.daily_prices;

create policy "authenticated users can read daily_prices"
on public.daily_prices
for select
to authenticated
using (true);

-- Currencies Policies

drop policy if exists "authenticated users can read currencies" on public.currencies;

create policy "authenticated users can read currencies"
on public.currencies
for select
to authenticated
using (true);