/*
    Table Schema Setup - for Holdings, Daily_Prices, Currencies, Trades 
*/

create table if not exists public.holdings (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    ticker text not null,
    shares_owned numeric(20,6) not null default 0 check (shares_owned >= 0),
    invested_amount numeric(20,6) not null default 0 check (invested_amount >= 0),
    currency text not null,
    platform text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, ticker, platform, currency)
);

create table if not exists public.daily_prices (
    id bigint generated by default as identity primary key,
    ticker text not null,
    price_per_share numeric(20,6) not null check (price_per_share >= 0),
    price_date date not null,
    created_at timestamptz not null default now(),
    unique (ticker, price_date)
);

create table if not exists public.currencies (
    id bigint generated by default as identity primary key,
    currency text not null,
    rate numeric(20,6) not null check (rate > 0),
    rate_date date not null,
    created_at timestamptz not null default now(),
    unique (currency, rate_date)
);

create table if not exists public.trades (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    holding_id bigint references public.holdings(id) on delete cascade,
    ticker text not null,
    trade_type text not null check (trade_type in ('BUY', 'SELL')),
    currency text not null,
    cash_amount numeric(20,6) not null check (cash_amount > 0),
    shares numeric(20,6) not null check (shares > 0),
    platform text not null,
    traded_at timestamptz not null,
    created_at timestamptz not null default now()
);

-- TBC Portfolio Snapshots Table, looks like some issues I will need to iron out later.
/*
create table if not exists public.portfolio_snapshots (
    id bigint generated by default as identity primary key,
    holding_id bigint not null references public.holdings(id) on delete cascade,
    snapshot_date date not null,
    shares_owned numeric(20,6) not null,
    invested_amount numeric(20,6) not null,
    price_per_share numeric(20,6) not null,
    fx_rate numeric(20,6) not null,
    market_value numeric(20,6) not null,
    market_value_sgd numeric(20,6) not null,
    unrealized_profit numeric(20,6) not null,
    unrealized_profit_sgd numeric(20,6) not null,
    created_at timestamptz not null default now(),
    unique (holding_id, snapshot_date)
);

*/

/*
    Indexes created for quick lookup for common queries - TO CHECK
*/

create index if not exists idx_holdings_user_id
    on public.holdings (user_id);

create index if not exists idx_holdings_user_id_ticker
    on public.holdings (user_id, ticker);

create index if not exists idx_trades_user_id
    on public.trades (user_id);

create index if not exists idx_trades_holding_id_traded_at
    on public.trades (holding_id, traded_at desc);

create index if not exists idx_trades_user_id_ticker_platform_currency
    on public.trades (user_id, ticker, platform, currency);

/*
    Triggers for auto-updates of latest updated data (timestamps) - TBC
*/

-- Trigger functions
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_holdings_set_updated_at on public.holdings;

create trigger trg_holdings_set_updated_at
before update on public.holdings
for each row
execute function public.set_updated_at();

/*
    BEFORE INSERT trigger:
    - resolve holding_id if missing
    - auto-create holding on BUY if it does not exist
    - reject SELL if holding does not exist
*/
create or replace function public.resolve_trade_holding()
returns trigger
language plpgsql
as $$
declare
    v_holding_id bigint;
    v_holding_user_id uuid;
begin
    -- If holding_id is already provided, validate it belongs to the same user
    if new.holding_id is not null then
        select h.user_id
        into v_holding_user_id
        from public.holdings h
        where h.id = new.holding_id;

        if v_holding_user_id is null then
            raise exception 'Holding % does not exist', new.holding_id;
        end if;

        if v_holding_user_id <> new.user_id then
            raise exception 'Holding % does not belong to user %', new.holding_id, new.user_id;
        end if;

        return new;
    end if;

    -- Try to find an existing holding for this user using ticker/platform/currency
    select h.id
    into v_holding_id
    from public.holdings h
    where h.user_id = new.user_id
      and h.ticker = new.ticker
      and h.platform = new.platform
      and h.currency = new.currency
    limit 1;

    if v_holding_id is not null then
        new.holding_id := v_holding_id;
        return new;
    end if;

    -- If not found and this is a BUY, create the holding automatically
    if new.trade_type = 'BUY' then
        insert into public.holdings (
            user_id,
            ticker,
            shares_owned,
            invested_amount,
            currency,
            platform
        )
        values (
            new.user_id,
            new.ticker,
            0,
            0,
            new.currency,
            new.platform
        )
        returning id into v_holding_id;

        new.holding_id := v_holding_id;
        return new;
    end if;

    -- If not found and this is a SELL, reject it
    raise exception
        'Cannot SELL: no holding exists for user %, ticker %, platform %, currency %',
        new.user_id, new.ticker, new.platform, new.currency;
end;
$$;

drop trigger if exists trg_trades_resolve_holding on public.trades;

create trigger trg_trades_resolve_holding
before insert on public.trades
for each row
execute function public.resolve_trade_holding();


/*
    AFTER INSERT trigger:
    - BUY: add shares and cash_amount to holdings
    - SELL: validate shares, reduce shares, reduce invested_amount by average cost basis
*/
create or replace function public.apply_trade_to_holding()
returns trigger
language plpgsql
as $$
declare
    v_current_shares numeric(20,6);
    v_current_invested numeric(20,6);
    v_holding_user_id uuid;
    v_avg_cost numeric(20,6);
    v_cost_reduction numeric(20,6);
begin
    select h.user_id, h.shares_owned, h.invested_amount
    into v_holding_user_id, v_current_shares, v_current_invested
    from public.holdings h
    where h.id = new.holding_id
    for update;

    if not found then
        raise exception 'Holding % not found for trade %', new.holding_id, new.id;
    end if;

    if v_holding_user_id <> new.user_id then
        raise exception 'Trade user_id does not match holding owner';
    end if;

    if new.trade_type = 'BUY' then
        update public.holdings
        set shares_owned = shares_owned + new.shares,
            invested_amount = invested_amount + new.cash_amount
        where id = new.holding_id;

        return new;
    end if;

    -- SELL logic
    if new.shares > v_current_shares then
        raise exception
            'Cannot SELL %.6f shares: holding only has %.6f shares',
            new.shares, v_current_shares;
    end if;

    if v_current_shares = 0 then
        raise exception 'Cannot SELL from holding % with zero shares', new.holding_id;
    end if;

    v_avg_cost := v_current_invested / v_current_shares;
    v_cost_reduction := new.shares * v_avg_cost;

    update public.holdings
    set shares_owned = shares_owned - new.shares,
        invested_amount = greatest(invested_amount - v_cost_reduction, 0)
    where id = new.holding_id;

    return new;
end;
$$;

drop trigger if exists trg_trades_apply_to_holding on public.trades;

create trigger trg_trades_apply_to_holding
after insert on public.trades
for each row
execute function public.apply_trade_to_holding();

/*
    Policies for Holdings and Trades (by user),
    and daily_prices and currencies (readable by authenticated users)
*/

-- RLS for all tables
alter table public.holdings enable row level security;
alter table public.trades enable row level security;
alter table public.daily_prices enable row level security;
alter table public.currencies enable row level security;

-- By User:
-- Holdings Policies

drop policy if exists "users can view own holdings" on public.holdings;

create policy "users can view own holdings"
on public.holdings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own holdings" on public.holdings;

create policy "users can insert own holdings"
on public.holdings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can update own holdings" on public.holdings;

create policy "users can update own holdings"
on public.holdings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own holdings" on public.holdings;

create policy "users can delete own holdings"
on public.holdings
for delete
to authenticated
using (auth.uid() = user_id);

-- Trades Policies

drop policy if exists "users can view own trades" on public.trades;

create policy "users can view own trades"
on public.trades
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own trades" on public.trades;

create policy "users can insert own trades"
on public.trades
for insert
to authenticated
with check (auth.uid() = user_id);

-- Public/Authenticated Reads
-- Daily_Prices Policies

drop policy if exists "authenticated users can read daily_prices" on public.daily_prices;

create policy "authenticated users can read daily_prices"
on public.daily_prices
for select
to authenticated
using (true);

-- Currencies Policies

drop policy if exists "authenticated users can read currencies" on public.currencies;

create policy "authenticated users can read currencies"
on public.currencies
for select
to authenticated
using (true);